version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: file-storage-mongodb
    ports:
      - "27020:27017"
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - backend-mongodb:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  backend-mongodb:
    driver: local
